spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class.name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=Northwind;encrypt=true;trustServerCertificate=true;
    username: spring_boot_user
    password: user
  jpa:
    hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


server:
  port: 8082

